[package]
name = "jak"
version = "0.1.0"
authors = ["Graham Brooks <graham@grahambrooks.com>"]
edition = "2018"

[dependencies]
clap = "~2.27.0"
reqwest = "~0.9.5"
serde_derive = "1.0.80"
serde = "1.0.80"
